class LoginError implements Exception {
  final String? message;

  const LoginError([this.message]);
}
